"""empty message

Revision ID: e2491efde8be
Revises: 47115b1c0054
Create Date: 2021-08-20 23:35:21.151891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2491efde8be'
down_revision = '47115b1c0054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'edited',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('planet', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.alter_column('planet', 'edited',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
